// <auto-generated />
namespace BitBookProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProfilePic_And_CoverPic_Field_Added_To_User_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProfilePic_And_CoverPic_Field_Added_To_User_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201612171357086_ProfilePic_And_CoverPic_Field_Added_To_User_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
