// <auto-generated />
namespace BitBookProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FriendStatus_Replaced_By_IsAccepted_Column_In_Friend_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FriendStatus_Replaced_By_IsAccepted_Column_In_Friend_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201612170302243_FriendStatus_Replaced_By_IsAccepted_Column_In_Friend_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
