// <auto-generated />
namespace BitBookProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DateTypeFixedForDateOfBirthInUserModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateTypeFixedForDateOfBirthInUserModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201612150439160_DateTypeFixedForDateOfBirthInUserModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
